# Define nossa imagem base
FROM jenkins/jenkins:lts-jdk11

# Define nosso usuario dentro do container
USER root

# Executa comandos para instalar o maven
RUN apt-get update

RUN echo "CURL =================================================================================="
RUN apt install curl

RUN echo "NVM AND NODEJS ================================================================================="
SHELL ["/bin/bash", "--login", "-c"]
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
RUN nvm install 16
RUN node --version

RUN echo "NPM ================================================================================="
RUN apt-get install -y npm
RUN npm --version

RUN echo "ANGULAR ================================================================================="
RUN npm install -g @angular/cli

# Instalando mailutils
RUN echo "MAIL UTILS =================================================================================="
RUN apt-get install -y mailutils

# Instalando chrome
RUN echo "CHROME =================================================================================="
RUN apt-get install -y wget
RUN wget --help

RUN curl -q -O https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN apt-get -y install ./google-chrome-stable_current_amd64.deb

# Limpa arquivos baixados com apt-get
RUN apt-get clean

USER jenkins