# Define nossa imagem base
FROM jenkins/jenkins:lts-jdk11

# Define nosso usuario dentro do container
USER root

# Executa comandos para instalar o maven
RUN apt-get update

RUN echo "NODEJS ================================================================================="
RUN apt-get install -y nodejs
RUN node --version

RUN echo "NPM ================================================================================="
RUN apt-get install -y npm
RUN npm --version

RUN echo "ANGULAR ================================================================================="
RUN npm install -g @angular/cli
RUN ng --version

# Instalando mailutils
RUN echo "MAIL UTILS =================================================================================="
RUN apt-get install -y mailutils

# Limpa arquivos baixados com apt-get
RUN apt-get clean

USER jenkins